### ISSUE TITLE
Проверка PR

### ISSUE THREAD

**Issue by mrvaldem** [mrvaldem/DoItBest#4]
Добрый день.
ДЗ 4-02
@DitrixNew прокомментируйте, плз
П.С.
@mrvaldem (для теста)

**Comment by DitriXEDT** [comment]
Вот так выглядит уведомление у меня
![image](https://user-images.githubusercontent.com/81814609/145476343-c606e031-b66a-474f-8f5e-bd70d05888ca.png)
